version: "3.12.3"

services:
  mytodoproject:
    # 현재 디렉토리를 빌드 컨텍스트로 사용하여 Docker 이미지를 빌드
    build:
      context: .
      dockerfile: dockerfile
      
    # 호스트의 8000번 포트를 컨테이너의 8000번 포트로 매핑
    ports:
      - "8000:8000"


